"""QueueMessage envelope tests (no DB) — routing keys + serialization."""

from __future__ import annotations

import uuid

import pytest

from career.queue.message import InvalidMessageError, QueueMessage

TENANT = str(uuid.uuid4())
AGG = str(uuid.uuid4())


def _valid(**over: object) -> QueueMessage:
    base = dict(
        tenant_id=TENANT, task_type="generate_cv", run_id="run-1",
        correlation_id="corr-1", idempotency_key="idem-1",
        aggregate_type="document", aggregate_id=AGG, payload={"job": "x"},
    )
    base.update(over)
    return QueueMessage(**base)  # type: ignore[arg-type]


def test_roundtrip_json() -> None:
    msg = _valid()
    again = QueueMessage.from_json(msg.to_json())
    assert again == msg


def test_all_routing_keys_present() -> None:
    assert _valid().validate() is not None


@pytest.mark.parametrize("key", ["tenant_id", "run_id", "correlation_id", "idempotency_key"])
def test_missing_routing_key_rejected(key: str) -> None:
    with pytest.raises(InvalidMessageError):
        _valid(**{key: "  "}).validate()


def test_tenant_id_must_be_uuid() -> None:
    with pytest.raises(InvalidMessageError):
        _valid(tenant_id="not-a-uuid").validate()


def test_aggregate_id_optional_but_uuid_when_present() -> None:
    assert _valid(aggregate_id=None).validate() is not None
    with pytest.raises(InvalidMessageError):
        _valid(aggregate_id="nope").validate()


def test_from_json_rejects_unknown_fields() -> None:
    import json
    bad = json.dumps({
        "tenant_id": TENANT, "task_type": "t", "run_id": "r",
        "correlation_id": "c", "idempotency_key": "i", "evil": 1,
    })
    with pytest.raises(InvalidMessageError):
        QueueMessage.from_json(bad)


def test_from_json_rejects_garbage() -> None:
    with pytest.raises(InvalidMessageError):
        QueueMessage.from_json("{not json")
    with pytest.raises(InvalidMessageError):
        QueueMessage.from_json("[]")


def test_message_id_autogenerated_and_stable_through_json() -> None:
    msg = _valid()
    assert msg.message_id
    assert QueueMessage.from_json(msg.to_json()).message_id == msg.message_id
